# Generated by Django 5.1 on 2024-08-11 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('title_en', models.CharField(max_length=256)),
                ('provider_course_id', models.PositiveIntegerField(verbose_name='id курса в провайдера')),
                ('summary', models.TextField(blank=True, null=True)),
                ('cover', models.TextField(blank=True, null=True, verbose_name='ссылка на изображение курса')),
                ('target_audience', models.TextField(blank=True, null=True, verbose_name='для кого')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='требования')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('total_units', models.PositiveIntegerField(blank=True, null=True)),
                ('lessons_count', models.PositiveIntegerField(blank=True, null=True)),
                ('quizzes_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('EASY', 'easy'), ('IN', 'Intermediate'), ('AD', 'Advanced')], default='EASY', max_length=10)),
                ('acquired_skills', models.TextField(blank=True, null=True, verbose_name='чему вы научитесь')),
                ('acquired_assets', models.TextField(blank=True, null=True, verbose_name='что вы получаете')),
                ('learning_format', models.TextField(blank=True, null=True, verbose_name='как проходит обучение')),
                ('course_type', models.CharField(max_length=10)),
                ('with_certificate', models.BooleanField(default=False)),
                ('canonical_url', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название провайдера')),
                ('code', models.CharField(max_length=10, verbose_name='код провайдера')),
                ('is_active', models.BooleanField(verbose_name='активно?')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_step_id', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('block', models.JSONField()),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_lesson_id', models.PositiveIntegerField(verbose_name='id урока в провайдера')),
                ('title', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cources.provider', verbose_name='провайдер'),
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_lesson_id', models.PositiveIntegerField(verbose_name='id секцию в провайдера')),
                ('position', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_unit_id', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.lessons')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.sections')),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_assignment_id', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.lessons')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.units')),
            ],
        ),
    ]
