# Generated by Django 5.1 on 2024-08-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_tag_id', models.IntegerField()),
                ('title', models.CharField(max_length=1024)),
                ('parent', models.TextField()),
                ('children', models.TextField()),
                ('parents', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
