# Generated by Django 5.1 on 2024-08-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0002_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='children',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='parent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='parents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
