# Generated by Django 5.0.8 on 2024-08-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0003_alter_tags_children_alter_tags_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
