# Generated by Django 5.0.8 on 2024-09-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0004_alter_courses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('EASY', 'easy'), ('IN', 'Intermediate'), ('AD', 'Advanced')], default='EASY', max_length=10, null=True),
        ),
    ]
