# Generated by Django 5.0.8 on 2024-09-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0005_alter_courses_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='difficulty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
