# Generated by Django 5.0.8 on 2024-09-02 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0006_alter_courses_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cources.sections'),
        ),
    ]
