# Generated by Django 5.0.8 on 2025-02-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0008_author_alter_courses_lessons_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
